"""Sandboxed code execution for TIR + RLVR (epic E1a, Phase 12).

The single runtime behind the *defining capability*: it runs a model-emitted
tool call and captures its output — the same executor serves inference-time tool
calls, the RLVR verifier's reward, and synthetic-data verification (three
customers, one sandbox — `docs/eval-plan.md` principle 4).

**Threat model (be honest about it).** RLVR code is generated by *our* model and
is adversarial-for-reward (it will try to game the checker) but not assumed
adversarial-for-exploit. This layer enforces **process isolation**: a fresh
subprocess (no shared interpreter state), a wall-clock timeout with process-group
kill, and POSIX resource limits (CPU seconds, address space). It does **not**
enforce network or filesystem isolation — that needs containers/nsjail and is
deferred (tracked in E1). The reward-layer anti-gaming judge (E1e) is the
complementary defense against gaming; this layer is the defense against hangs,
crashes, and runaway memory. POSIX-only (Linux/macOS); ``preexec_fn`` limits are
skipped where unavailable.
"""

from __future__ import annotations

import json
import os
import shutil
import signal
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

DEFAULT_TIMEOUT_S = 5.0
DEFAULT_MEMORY_MB = 2048  # generous — numpy/scipy reserve large virtual address space
MAX_OUTPUT_CHARS = 8192  # truncate captured output (context safety + a reward-hacking surface)


@dataclass(frozen=True)
class ExecutionResult:
    """Outcome of one sandboxed run. ``ok`` iff the process exited 0 in time."""

    ok: bool
    stdout: str
    stderr: str
    returncode: int | None  # None if killed (timeout / limit)
    timed_out: bool
    duration_s: float

    @property
    def output(self) -> str:
        """stdout if the run succeeded, else stderr (the traceback) — what the
        model sees injected as the tool result, so it can read errors and retry."""
        return self.stdout if self.ok else (self.stderr or self.stdout)


def _truncate(s: str) -> str:
    return s if len(s) <= MAX_OUTPUT_CHARS else s[:MAX_OUTPUT_CHARS] + "\n[...truncated]"


def _rlimit_preexec(cpu_s: int, mem_bytes: int | None) -> Callable[[], None] | None:
    """A child-side hook setting CPU + address-space rlimits. None off-POSIX."""
    try:
        import resource
    except ImportError:  # pragma: no cover — non-POSIX
        return None

    def _apply() -> None:
        resource.setrlimit(resource.RLIMIT_CPU, (cpu_s, cpu_s))
        if mem_bytes is not None:
            resource.setrlimit(resource.RLIMIT_AS, (mem_bytes, mem_bytes))

    return _apply


def _run(
    argv: list[str], *, cwd: str, timeout_s: float, memory_mb: int | None
) -> ExecutionResult:
    cpu_s = int(timeout_s) + 1  # CPU-time backstop just past the wall-clock deadline
    mem_bytes = memory_mb * 1024 * 1024 if memory_mb else None
    # Minimal env: keep PATH (find interpreters/octave), drop the rest. Not a
    # network jail — just a smaller surface + reproducible hashing.
    env = {"PATH": os.environ.get("PATH", ""), "PYTHONHASHSEED": "0", "OPENBLAS_NUM_THREADS": "1"}
    start = time.monotonic()
    # start_new_session=True makes the child a process-group leader, so on timeout we
    # kill the WHOLE group — otherwise a grandchild the code spawned outlives the
    # timeout (subprocess.run's timeout only SIGKILLs the direct child). Popen +
    # killpg is what actually reaps forked/spawned escapees.
    proc = subprocess.Popen(
        argv,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        start_new_session=True,
        preexec_fn=_rlimit_preexec(cpu_s, mem_bytes),
        env=env,
    )
    try:
        stdout, stderr = proc.communicate(timeout=timeout_s)
        return ExecutionResult(
            ok=proc.returncode == 0,
            stdout=_truncate(stdout),
            stderr=_truncate(stderr),
            returncode=proc.returncode,
            timed_out=False,
            duration_s=time.monotonic() - start,
        )
    except subprocess.TimeoutExpired:
        _kill_group(proc)
        stdout, stderr = proc.communicate()  # drain the pipes after the kill
        return ExecutionResult(
            ok=False,
            stdout=_truncate(stdout or ""),
            stderr=_truncate((stderr or "") + f"\n[timed out after {timeout_s}s]"),
            returncode=None,
            timed_out=True,
            duration_s=time.monotonic() - start,
        )


def _kill_group(proc: subprocess.Popen) -> None:
    """SIGKILL the child's whole process group (reaps grandchildren it spawned)."""
    try:
        os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
    except (ProcessLookupError, PermissionError):  # already gone / not our group
        proc.kill()


def run_python(
    code: str,
    *,
    timeout_s: float = DEFAULT_TIMEOUT_S,
    memory_mb: int | None = DEFAULT_MEMORY_MB,
    setup: str = "",
) -> ExecutionResult:
    """Execute ``code`` in an isolated Python subprocess; capture stdout/stderr.

    ``setup`` is prepended (e.g. imports or a checker harness the caller controls);
    it shares the child's namespace with ``code``.
    """
    src = f"{setup}\n{code}" if setup else code
    with tempfile.TemporaryDirectory(prefix="lithos_sbx_") as td:
        script = Path(td) / "snippet.py"
        script.write_text(src, encoding="utf-8")
        return _run(
            [sys.executable, str(script)], cwd=td, timeout_s=timeout_s, memory_mb=memory_mb
        )


def octave_available() -> bool:
    return shutil.which("octave") is not None


def run_octave(
    code: str, *, timeout_s: float = DEFAULT_TIMEOUT_S, memory_mb: int | None = DEFAULT_MEMORY_MB
) -> ExecutionResult:
    """Execute ``code`` with Octave (MATLAB-syntax tool). Degrades gracefully to a
    clear not-ok result if the ``octave`` binary is absent, so callers/tests never
    crash on a box without it."""
    if not octave_available():
        return ExecutionResult(
            ok=False,
            stdout="",
            stderr="octave not installed (install `octave`; it is the MATLAB-syntax runtime)",
            returncode=None,
            timed_out=False,
            duration_s=0.0,
        )
    with tempfile.TemporaryDirectory(prefix="lithos_sbx_") as td:
        script = Path(td) / "snippet.m"
        script.write_text(code, encoding="utf-8")
        return _run(
            ["octave", "--no-gui", "--norc", "--quiet", str(script)],
            cwd=td,
            timeout_s=timeout_s,
            memory_mb=memory_mb,
        )


# ---------------------------------------------------------------------------
# Assay runtime (v0 shim). The real executor is the embedded Assay engine
# (assay-vision.md); until it ships, this shim covers the symbolic-calculus
# template families so the wire format, training data, and rollouts can run end
# to end. The IR payload is JSON: {"task": <template_id>, "inputs": {...},
# "missing_inputs": [...]}. The shim COMPILES the IR into a deterministic sympy
# program — the template owns the method, the model never writes it — and runs
# it through the same subprocess sandbox as `python` (timeout/rlimits/isolation
# for free). Everything outside the registry fails loud with the known-template
# list, which is exactly the feedback an out-of-coverage rollout should see.

_ASSAY_V0_PROGRAMS: dict[str, str] = {
    # each entry: sympy statements binding `result` from validated `inputs`
    "differentiate.univariate": "result = {'derivative': str(sp.diff(expr, var))}",
    "integrate.univariate": "result = {'antiderivative': str(sp.integrate(expr, var))}",
    "limit.of_function": "result = {'limit_value': str(sp.limit(expr, var, point))}",
    "derivative.at_point": "result = {'derivative_value': str(sp.limit(expr, var, point))}",
    "solve_equation.univariate": "result = {'roots': [str(r) for r in sp.solve(expr, var)]}",
}

_ASSAY_PRELUDE = """\
import json, sympy as sp
from sympy.parsing.sympy_parser import parse_expr
inputs = json.loads({inputs_json!r})
var = sp.Symbol(inputs["variable"])
expr = parse_expr(inputs["expression"], local_dict={{inputs["variable"]: var}})
_p = inputs.get("point")
point = sp.oo if _p in ("oo", "inf") else (-sp.oo if _p == "-oo" else sp.sympify(_p) if _p is not None else None)
{program}
print(json.dumps(result))
"""


def run_assay(
    code: str, *, timeout_s: float = DEFAULT_TIMEOUT_S, memory_mb: int | None = DEFAULT_MEMORY_MB
) -> ExecutionResult:
    """Execute an Assay IR (JSON in ``code``) against the v0 template registry.

    Malformed IR / unknown template / missing inputs return ``ok=False`` with an
    explanatory message rather than raising — the model reads the injected error
    and can retry or fall back to the ``python`` runtime (the head/tail doctrine).
    """

    def refuse(msg: str) -> ExecutionResult:
        return ExecutionResult(
            ok=False, stdout="", stderr=msg, returncode=None, timed_out=False, duration_s=0.0
        )

    try:
        ir = json.loads(code)
    except json.JSONDecodeError as e:
        return refuse(f"assay: IR is not valid JSON ({e})")
    if not isinstance(ir, dict) or not isinstance(ir.get("task"), str):
        return refuse("assay: IR must be an object with a string 'task' field")
    if ir.get("missing_inputs"):
        return refuse(
            f"assay: cannot execute with missing_inputs={ir['missing_inputs']} — "
            "resolve or ask for them; never invent values"
        )
    program = _ASSAY_V0_PROGRAMS.get(ir["task"])
    if program is None:
        return refuse(
            f"assay: template {ir['task']!r} not in the v0 registry "
            f"{sorted(_ASSAY_V0_PROGRAMS)}; use the python runtime for uncovered tasks"
        )
    inputs = ir.get("inputs")
    if not isinstance(inputs, dict) or not all(
        isinstance(inputs.get(k), str) for k in ("expression", "variable")
    ):
        return refuse("assay: 'inputs' must carry string 'expression' and 'variable'")
    script = _ASSAY_PRELUDE.format(inputs_json=json.dumps(inputs), program=program)
    return run_python(script, timeout_s=timeout_s, memory_mb=memory_mb)


# Runtime dispatch by the tool-call open-token name (see docs/tir-format.md §2).
RUNTIMES: dict[str, Callable[..., ExecutionResult]] = {
    "python": run_python,
    "octave": run_octave,
    "assay": run_assay,
}


def run_tool(runtime: str, code: str, **kw: object) -> ExecutionResult:
    """Route a tool call to its runtime by name (``python``/``octave``/``assay``)."""
    if runtime not in RUNTIMES:
        raise ValueError(f"unknown runtime {runtime!r}; have {sorted(RUNTIMES)}")
    return RUNTIMES[runtime](code, **kw)
