"""Sandboxed code execution for TIR + RLVR (epic E1a, Phase 12).

The single runtime behind the *defining capability*: it runs a model-emitted
tool call and captures its output — the same executor serves inference-time tool
calls, the RLVR verifier's reward, and synthetic-data verification (three
customers, one sandbox — `docs/eval-plan.md` principle 4).

**Threat model (be honest about it).** RLVR code is generated by *our* model and
is adversarial-for-reward (it will try to game the checker) but not assumed
adversarial-for-exploit. This layer enforces **process isolation**: a fresh
subprocess (no shared interpreter state), a wall-clock timeout with process-group
kill, and POSIX resource limits (CPU seconds, address space). It does **not**
enforce network or filesystem isolation — that needs containers/nsjail and is
deferred (tracked in E1). The reward-layer anti-gaming judge (E1e) is the
complementary defense against gaming; this layer is the defense against hangs,
crashes, and runaway memory. POSIX-only (Linux/macOS); ``preexec_fn`` limits are
skipped where unavailable.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import signal
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable
from dataclasses import dataclass
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Any, Final

DEFAULT_TIMEOUT_S = 5.0
DEFAULT_MEMORY_MB = 2048  # generous — numpy/scipy reserve large virtual address space
MAX_OUTPUT_CHARS = 8192  # truncate captured output (context safety + a reward-hacking surface)

#: The libraries a `kind=code` checker (and a TIR tool call) may rely on. Pinned with
#: Chisel — a key computed in the data factory must match the key GRPO checks and the
#: answer the server serves. See `docs/chisel-f7-response.md` §3.
CHECKER_IMPORT_SET: Final[frozenset[str]] = frozenset({"stdlib", "numpy", "scipy", "sympy"})

_PINNED_PACKAGES: Final[tuple[str, ...]] = ("numpy", "scipy", "sympy")


def _package_version(name: str) -> str:
    try:
        return version(name)
    except PackageNotFoundError:  # pragma: no cover - a missing core dep is a broken install
        return "MISSING"


def tool_env_fingerprint() -> dict[str, Any]:
    """Everything that can change a tool call's *answer*, in one dict.

    A composite model's identity includes ``tool_env_sha`` (`docs/composite-model-layer.md`
    §7.1) because a number computed by the sandbox is part of the model's output. Bump
    any of these and the served model is a different model, whatever the weights say.
    """
    return {
        "python": ".".join(str(v) for v in sys.version_info[:3]),
        "packages": {p: _package_version(p) for p in _PINNED_PACKAGES},
        "import_set": sorted(CHECKER_IMPORT_SET),
        "timeout_s": DEFAULT_TIMEOUT_S,
        "memory_mb": DEFAULT_MEMORY_MB,
        "max_output_chars": MAX_OUTPUT_CHARS,
        # Determinism knobs: the reason a key computed in Chisel matches one computed here.
        "env": {"PYTHONHASHSEED": "0", "OPENBLAS_NUM_THREADS": "1"},
    }


def tool_env_sha() -> str:
    """Stable sha256 of :func:`tool_env_fingerprint` — the identity tuple's 4th component."""
    blob = json.dumps(tool_env_fingerprint(), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class ExecutionResult:
    """Outcome of one sandboxed run. ``ok`` iff the process exited 0 in time."""

    ok: bool
    stdout: str
    stderr: str
    returncode: int | None  # None if killed (timeout / limit)
    timed_out: bool
    duration_s: float

    @property
    def output(self) -> str:
        """stdout if the run succeeded, else stderr (the traceback) — what the
        model sees injected as the tool result, so it can read errors and retry."""
        return self.stdout if self.ok else (self.stderr or self.stdout)


def _truncate(s: str) -> str:
    return s if len(s) <= MAX_OUTPUT_CHARS else s[:MAX_OUTPUT_CHARS] + "\n[...truncated]"


def _rlimit_preexec(cpu_s: int, mem_bytes: int | None) -> Callable[[], None] | None:
    """A child-side hook setting CPU + address-space rlimits. None off-POSIX."""
    try:
        import resource
    except ImportError:  # pragma: no cover — non-POSIX
        return None

    def _apply() -> None:
        resource.setrlimit(resource.RLIMIT_CPU, (cpu_s, cpu_s))
        if mem_bytes is not None:
            resource.setrlimit(resource.RLIMIT_AS, (mem_bytes, mem_bytes))

    return _apply


def _run(
    argv: list[str], *, cwd: str, timeout_s: float, memory_mb: int | None
) -> ExecutionResult:
    cpu_s = int(timeout_s) + 1  # CPU-time backstop just past the wall-clock deadline
    mem_bytes = memory_mb * 1024 * 1024 if memory_mb else None
    # Minimal env: keep PATH (find interpreters/octave), drop the rest. Not a
    # network jail — just a smaller surface + reproducible hashing.
    env = {"PATH": os.environ.get("PATH", ""), "PYTHONHASHSEED": "0", "OPENBLAS_NUM_THREADS": "1"}
    start = time.monotonic()
    # start_new_session=True makes the child a process-group leader, so on timeout we
    # kill the WHOLE group — otherwise a grandchild the code spawned outlives the
    # timeout (subprocess.run's timeout only SIGKILLs the direct child). Popen +
    # killpg is what actually reaps forked/spawned escapees.
    proc = subprocess.Popen(
        argv,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        start_new_session=True,
        preexec_fn=_rlimit_preexec(cpu_s, mem_bytes),
        env=env,
    )
    try:
        stdout, stderr = proc.communicate(timeout=timeout_s)
        return ExecutionResult(
            ok=proc.returncode == 0,
            stdout=_truncate(stdout),
            stderr=_truncate(stderr),
            returncode=proc.returncode,
            timed_out=False,
            duration_s=time.monotonic() - start,
        )
    except subprocess.TimeoutExpired:
        _kill_group(proc)
        stdout, stderr = proc.communicate()  # drain the pipes after the kill
        return ExecutionResult(
            ok=False,
            stdout=_truncate(stdout or ""),
            stderr=_truncate((stderr or "") + f"\n[timed out after {timeout_s}s]"),
            returncode=None,
            timed_out=True,
            duration_s=time.monotonic() - start,
        )


def _kill_group(proc: subprocess.Popen) -> None:
    """SIGKILL the child's whole process group (reaps grandchildren it spawned)."""
    try:
        os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
    except (ProcessLookupError, PermissionError):  # already gone / not our group
        proc.kill()


def run_python(
    code: str,
    *,
    timeout_s: float = DEFAULT_TIMEOUT_S,
    memory_mb: int | None = DEFAULT_MEMORY_MB,
    setup: str = "",
) -> ExecutionResult:
    """Execute ``code`` in an isolated Python subprocess; capture stdout/stderr.

    ``setup`` is prepended (e.g. imports or a checker harness the caller controls);
    it shares the child's namespace with ``code``.
    """
    src = f"{setup}\n{code}" if setup else code
    with tempfile.TemporaryDirectory(prefix="lithos_sbx_") as td:
        script = Path(td) / "snippet.py"
        script.write_text(src, encoding="utf-8")
        return _run(
            [sys.executable, str(script)], cwd=td, timeout_s=timeout_s, memory_mb=memory_mb
        )


def octave_available() -> bool:
    return shutil.which("octave") is not None


def run_octave(
    code: str, *, timeout_s: float = DEFAULT_TIMEOUT_S, memory_mb: int | None = DEFAULT_MEMORY_MB
) -> ExecutionResult:
    """Execute ``code`` with Octave (MATLAB-syntax tool). Degrades gracefully to a
    clear not-ok result if the ``octave`` binary is absent, so callers/tests never
    crash on a box without it."""
    if not octave_available():
        return ExecutionResult(
            ok=False,
            stdout="",
            stderr="octave not installed (install `octave`; it is the MATLAB-syntax runtime)",
            returncode=None,
            timed_out=False,
            duration_s=0.0,
        )
    with tempfile.TemporaryDirectory(prefix="lithos_sbx_") as td:
        script = Path(td) / "snippet.m"
        script.write_text(code, encoding="utf-8")
        return _run(
            ["octave", "--no-gui", "--norc", "--quiet", str(script)],
            cwd=td,
            timeout_s=timeout_s,
            memory_mb=memory_mb,
        )


# Runtime dispatch by the tool-call open-token name (see docs/tir-format.md §2).
RUNTIMES: dict[str, Callable[..., ExecutionResult]] = {"python": run_python, "octave": run_octave}


def run_tool(runtime: str, code: str, **kw: object) -> ExecutionResult:
    """Route a tool call to its runtime by name (``python``/``octave``)."""
    if runtime not in RUNTIMES:
        raise ValueError(f"unknown runtime {runtime!r}; have {sorted(RUNTIMES)}")
    return RUNTIMES[runtime](code, **kw)
